### ISSUE TITLE
blocking calls at custom_components/sems2mqtt/__init__.py

### ISSUE THREAD

**Issue by grehund** [bouwew/sems2mqtt#19]
Logger: homeassistant.util.async_
Source: util/async_.py:144
First occurred: 8:46:23 AM (53 occurrences)
Last logged: 11:16:53 AM

Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for sems2mqtt doing blocking calls at custom_components/sems2mqtt/__init__.py, line 183: time.sleep((2*i) ** 2)

**Comment by bouwew** [comment]
Sorry, I didn't notice your Issues until today.

I will have a look at this tonight.

**Comment by bouwew** [comment]
Can you please test v0.4.8b0?
Does the change I made solve the issue?

**Comment by grehund** [comment]
I have just installed 0.4.8b0. The error hasn't reappeared in the logs after a restart. I will check again in 12 hours.

**Comment by grehund** [comment]
Issue is resolved by 0.4.8b0, thanks. Working without error on 2022.3.

**Comment by bouwew** [comment]
Good to read, thanks! I'll release v0.4.8.
