### ISSUE TITLE
Only 1 inversor showing

### ISSUE THREAD

**Issue by lucas685** [bouwew/sems2mqtt#22]
Hi there, i have two goodwe inversors in the SEMS page, but once i have configured the integration, only the entities from the Inversor 01 are showing up, can someone help me please? I think its something from the API not getting the 2nd inversor information.

**Comment by bouwew** [comment]
Sorry, I will only solve bugs in the present code. I have no plans to add support for a 2nd inverter.

For two inverters, I suggest you switch to using https://github.com/TimSoethout/goodwe-sems-home-assistant
