### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by CervDotBe** [bouwew/sems2mqtt#4]
Logger: homeassistant
Source: custom_components/sems2mqtt/__init__.py:353
First occurred: 2:33:13 PM (1 occurrences)
Last logged: 2:33:13 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sems2mqtt/__init__.py", line 353, in async_get_sems_data
    payload = locals()[payload]
KeyError: 'payload_dc_voltage_str_1'

**Comment by bouwew** [comment]
Solved by #5
